name: "Build + Test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    strategy:
      max-parallel: 1
      matrix:
        os:
          - windows-latest
          - windows-2022
          - windows2019
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
          - macos-12
          - macos-11
          - macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Basic Content Test
        uses: ./
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: test
      - name: Test `@ping`
        uses: ./
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: Hey there <@211894927997534208>
      - name: Test with JSON Payload Provided
        uses: ./
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          raw-data: __tests__/data/content-only.json
      - name: Upload File
        uses: ./
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          filename: __tests__/data/content-only.json
          username: Bill
          content: You should definintely be able to do this
          avatar-url: https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256
      - name: Discord Webhook Action With Embed
        uses: ./
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: Bill
          avatar-url: https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256
          embed-title: "Foo"
          embed-description: "Bar [test](https://google.com)"
          embed-author-name: "Bill"
          embed-author-icon-url: "https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256"
          embed-author-url: "https://google.com"
          embed-thumbnail-url: "https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256"
          embed-image-url: "https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256"
          embed-footer-icon-url: "https://cdn.discordapp.com/avatars/742807869023322232/dd41912939ffccbea0276f70688fa0ec.webp?size=256"
          embed-footer-text: "Foot text [test](https://google.com)"
          embed-color: 15430476
          embed-timestamp: "2021-09-24T02:17:53+0000"
